# Generated by Django 6.0.8 on 2026-08-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Rent', 'Rent'), ('Electricity', 'Electricity'), ('Internet', 'Internet'), ('Stationery', 'Stationery'), ('Maintenance', 'Maintenance'), ('Marketing', 'Marketing'), ('Other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
