# Generated by Django 6.0.8 on 2026-08-09 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('teacher_diary', '0001_initial'),
        ('teachers', '0002_teachersalary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-date', 'teacher__first_name']},
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='teachers.teacher'),
        ),
    ]
