# Generated by Django 6.0.8 on 2026-08-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_diary', '0002_alter_diaryentry_options_alter_diaryentry_classroom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Diary Entry', 'verbose_name_plural': 'Diary Entries'},
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='description',
            field=models.TextField(verbose_name='What was taught'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='topic',
            field=models.CharField(max_length=255),
        ),
    ]
