# Generated by Django 6.0.8 on 2026-08-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teachersalary'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teachersalary',
            name='unique_teacher_salary_month',
        ),
        migrations.DeleteModel(
            name='TeacherSalary',
        ),
    ]
