# Generated by Django 6.0.8 on 2026-08-19 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0003_remove_fee_amount_fee_admission_fee_fee_amount_paid_and_more'),
        ('students', '0005_student_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fee',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='fee',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='fee',
            constraint=models.UniqueConstraint(fields=('student', 'month', 'year'), name='unique_student_month_year_fee'),
        ),
    ]
